### ISSUE TITLE
* in pom causes error

### ISSUE THREAD

**Issue by difranco** [mrdon/maven-yamlpom-plugin#4]
In a pom that contains the following:

```
resources:
  - directory: resources
    includes:
      - **/*
```

I get this error:

```
Embedded error: Invalid YAML
while scanning an alias; expected alphabetic or numeric character, but found but found *
```
